services:
  postgres:
    image: postgres:latest
    container_name: postgres-sandbox
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dbadmin
    ports:
      - "5432:5432"

  keycloak:
    image: keycloak/keycloak:latest
    container_name: keycloak-sandbox
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: sandbox_keycloak
      DB_USER: dbadmin
      DB_PASSWORD: secret
    ports:
      - "8081:8080"
    command:
      - start-dev
    depends_on:
      - postgres