services:
  postgres:
    image: postgres:latest
    container_name: postgres-sandbox
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dbadmin
    volumes:
      - ../scripts/database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  keycloak:
    image: keycloak/keycloak:latest
    container_name: keycloak-sandbox
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: sandbox
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: dbadmin
      KC_DB_PASSWORD: secret
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/sandbox_realm.json
    ports:
      - "8081:8080"
    command:
      - start-dev
    volumes:
      - ../scripts/keycloak:/opt/keycloak/data/import
    depends_on:
      - postgres

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog-sandbox
    ports:
      - "8025:8025"
      - "1025:1025"